/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HeavyComputation */

#ifndef _Included_HeavyComputation
#define _Included_HeavyComputation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HeavyComputation
 * Method:    multiplyMatricesNative
 * Signature: ([D[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HeavyComputation_multiplyMatricesNative
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
