server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/fbdb
spring.datasource.username=root
spring.datasource.password=@Suraj1995#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
